!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  Pseg_dis_thre: 0.02
  Pseg_iter_num: 1000
  Pseg_size_min: 0.1
  RG_curve_thre: 0.1
  RG_neighbor_n: 30
  RG_smooth_thre_deg: 5.0
  boundEstRad: 30.0
  centroid_dis_max: 0.25
  centroid_dis_min: 0.15
  circle_radius: 0.12
  circle_seg_thre: 0.02
  cluster_size_max: 20.0
  cluster_size_min: 2.0
  cluster_tole: 0.05
  gauss_conv_radius: 0.02
  gauss_conv_radius2: 0.02
  gauss_k_sigma: 3.0
  gauss_k_sigma2: 3.0
  gauss_k_thre: 0.05
  gauss_k_thre2: 0.05
  gauss_k_thre_rt_sigma: 3.0
  gauss_k_thre_rt_sigma2: 3.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      Pseg_dis_thre: 0.02
      Pseg_iter_num: 1000
      Pseg_size_min: 0.1
      RG_curve_thre: 0.1
      RG_neighbor_n: 30
      RG_smooth_thre_deg: 5.0
      boundEstRad: 30.0
      centroid_dis_max: 0.25
      centroid_dis_min: 0.15
      circle_radius: 0.12
      circle_seg_thre: 0.02
      cluster_size_max: 20.0
      cluster_size_min: 2.0
      cluster_tole: 0.05
      gauss_conv_radius: 0.02
      gauss_conv_radius2: 0.02
      gauss_k_sigma: 3.0
      gauss_k_sigma2: 3.0
      gauss_k_thre: 0.05
      gauss_k_thre2: 0.05
      gauss_k_thre_rt_sigma: 3.0
      gauss_k_thre_rt_sigma2: 3.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      i_filter_out_max: 200.0
      i_filter_out_min: 0.0
      id: 0
      min_centers_found: 4
      name: Default
      normEstRad: 50.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      remove_x_max: 1.0
      remove_x_min: -1.0
      rmse_tpl2ukn_thre: 0.03
      rmse_ukn2tpl_thre: 0.03
      sor_MeanK: 10
      sor_StddevMulThresh: 1
      state: true
      type: ''
      voxel_grid_size: 0.05
    state: []
  i_filter_out_max: 200.0
  i_filter_out_min: 0.0
  min_centers_found: 4
  normEstRad: 50.0
  remove_x_max: 1.0
  remove_x_min: -1.0
  rmse_tpl2ukn_thre: 0.03
  rmse_ukn2tpl_thre: 0.03
  sor_MeanK: 10
  sor_StddevMulThresh: 1
  voxel_grid_size: 0.05
state: []
